// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bank_account_type::BankAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `bank_account`.
///
/// Obtain a handle from the [`BankAccountTableAccess::bank_account`] method on [`super::RemoteTables`],
/// like `ctx.db.bank_account()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bank_account().on_insert(...)`.
pub struct BankAccountTableHandle<'ctx> {
    imp: __sdk::TableHandle<BankAccount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `bank_account`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BankAccountTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BankAccountTableHandle`], which mediates access to the table `bank_account`.
    fn bank_account(&self) -> BankAccountTableHandle<'_>;
}

impl BankAccountTableAccess for super::RemoteTables {
    fn bank_account(&self) -> BankAccountTableHandle<'_> {
        BankAccountTableHandle {
            imp: self.imp.get_table::<BankAccount>("bank_account"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BankAccountInsertCallbackId(__sdk::CallbackId);
pub struct BankAccountDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BankAccountTableHandle<'ctx> {
    type Row = BankAccount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BankAccount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BankAccountInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BankAccountInsertCallbackId {
        BankAccountInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BankAccountInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BankAccountDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BankAccountDeleteCallbackId {
        BankAccountDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BankAccountDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BankAccount>("bank_account");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct BankAccountUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BankAccountTableHandle<'ctx> {
    type UpdateCallbackId = BankAccountUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BankAccountUpdateCallbackId {
        BankAccountUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BankAccountUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BankAccount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BankAccount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `bank_account`,
/// which allows point queries on the field of the same name
/// via the [`BankAccountIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.bank_account().identity().find(...)`.
pub struct BankAccountIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BankAccount, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BankAccountTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `bank_account`.
    pub fn identity(&self) -> BankAccountIdentityUnique<'ctx> {
        BankAccountIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BankAccountIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<BankAccount> {
        self.imp.find(col_val)
    }
}
