// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::condition_type::Condition;
use super::condition_type_type::ConditionType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `condition`.
///
/// Obtain a handle from the [`ConditionTableAccess::condition`] method on [`super::RemoteTables`],
/// like `ctx.db.condition()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.condition().on_insert(...)`.
pub struct ConditionTableHandle<'ctx> {
    imp: __sdk::TableHandle<Condition>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `condition`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConditionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConditionTableHandle`], which mediates access to the table `condition`.
    fn condition(&self) -> ConditionTableHandle<'_>;
}

impl ConditionTableAccess for super::RemoteTables {
    fn condition(&self) -> ConditionTableHandle<'_> {
        ConditionTableHandle {
            imp: self.imp.get_table::<Condition>("condition"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConditionInsertCallbackId(__sdk::CallbackId);
pub struct ConditionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConditionTableHandle<'ctx> {
    type Row = Condition;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Condition> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConditionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConditionInsertCallbackId {
        ConditionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConditionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConditionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConditionDeleteCallbackId {
        ConditionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConditionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Condition>("condition");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ConditionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConditionTableHandle<'ctx> {
    type UpdateCallbackId = ConditionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConditionUpdateCallbackId {
        ConditionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConditionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Condition>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Condition>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `condition`,
/// which allows point queries on the field of the same name
/// via the [`ConditionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.condition().id().find(...)`.
pub struct ConditionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Condition, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConditionTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `condition`.
    pub fn id(&self) -> ConditionIdUnique<'ctx> {
        ConditionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConditionIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Condition> {
        self.imp.find(col_val)
    }
}
