// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Containment {
    pub id: u64,
    pub container_id: u64,
    pub contained_id: u64,
    pub depth: u8,
    pub slot_index: Option<u8>,
}

impl __sdk::InModule for Containment {
    type Module = super::RemoteModule;
}
