// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::containment_type::Containment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `containment`.
///
/// Obtain a handle from the [`ContainmentTableAccess::containment`] method on [`super::RemoteTables`],
/// like `ctx.db.containment()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.containment().on_insert(...)`.
pub struct ContainmentTableHandle<'ctx> {
    imp: __sdk::TableHandle<Containment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `containment`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContainmentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContainmentTableHandle`], which mediates access to the table `containment`.
    fn containment(&self) -> ContainmentTableHandle<'_>;
}

impl ContainmentTableAccess for super::RemoteTables {
    fn containment(&self) -> ContainmentTableHandle<'_> {
        ContainmentTableHandle {
            imp: self.imp.get_table::<Containment>("containment"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContainmentInsertCallbackId(__sdk::CallbackId);
pub struct ContainmentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ContainmentTableHandle<'ctx> {
    type Row = Containment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Containment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContainmentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainmentInsertCallbackId {
        ContainmentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContainmentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContainmentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContainmentDeleteCallbackId {
        ContainmentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContainmentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Containment>("containment");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ContainmentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContainmentTableHandle<'ctx> {
    type UpdateCallbackId = ContainmentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContainmentUpdateCallbackId {
        ContainmentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContainmentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Containment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Containment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `containment`,
/// which allows point queries on the field of the same name
/// via the [`ContainmentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.containment().id().find(...)`.
pub struct ContainmentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Containment, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContainmentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `containment`.
    pub fn id(&self) -> ContainmentIdUnique<'ctx> {
        ContainmentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContainmentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Containment> {
        self.imp.find(col_val)
    }
}
