// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTestRoomArgs {}

impl From<CreateTestRoomArgs> for super::Reducer {
    fn from(args: CreateTestRoomArgs) -> Self {
        Self::CreateTestRoom
    }
}

impl __sdk::InModule for CreateTestRoomArgs {
    type Module = super::RemoteModule;
}

pub struct CreateTestRoomCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_test_room`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_test_room {
    /// Request that the remote module invoke the reducer `create_test_room` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_test_room`] callbacks.
    fn create_test_room(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_test_room`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateTestRoomCallbackId`] can be passed to [`Self::remove_on_create_test_room`]
    /// to cancel the callback.
    fn on_create_test_room(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> CreateTestRoomCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_test_room`],
    /// causing it not to run in the future.
    fn remove_on_create_test_room(&self, callback: CreateTestRoomCallbackId);
}

impl create_test_room for super::RemoteReducers {
    fn create_test_room(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_test_room", CreateTestRoomArgs {})
    }
    fn on_create_test_room(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> CreateTestRoomCallbackId {
        CreateTestRoomCallbackId(self.imp.on_reducer(
            "create_test_room",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateTestRoom {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_create_test_room(&self, callback: CreateTestRoomCallbackId) {
        self.imp.remove_on_reducer("create_test_room", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_test_room`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_test_room {
    /// Set the call-reducer flags for the reducer `create_test_room` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_test_room(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_test_room for super::SetReducerFlags {
    fn create_test_room(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_test_room", flags);
    }
}
