// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTestEntityArgs {
    pub name: String,
}

impl From<CreateTestEntityArgs> for super::Reducer {
    fn from(args: CreateTestEntityArgs) -> Self {
        Self::CreateTestEntity { name: args.name }
    }
}

impl __sdk::InModule for CreateTestEntityArgs {
    type Module = super::RemoteModule;
}

pub struct CreateTestEntityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_test_entity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_test_entity {
    /// Request that the remote module invoke the reducer `create_test_entity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_test_entity`] callbacks.
    fn create_test_entity(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_test_entity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateTestEntityCallbackId`] can be passed to [`Self::remove_on_create_test_entity`]
    /// to cancel the callback.
    fn on_create_test_entity(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateTestEntityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_test_entity`],
    /// causing it not to run in the future.
    fn remove_on_create_test_entity(&self, callback: CreateTestEntityCallbackId);
}

impl create_test_entity for super::RemoteReducers {
    fn create_test_entity(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_test_entity", CreateTestEntityArgs { name })
    }
    fn on_create_test_entity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateTestEntityCallbackId {
        CreateTestEntityCallbackId(self.imp.on_reducer(
            "create_test_entity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateTestEntity { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_create_test_entity(&self, callback: CreateTestEntityCallbackId) {
        self.imp.remove_on_reducer("create_test_entity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_test_entity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_test_entity {
    /// Set the call-reducer flags for the reducer `create_test_entity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_test_entity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_test_entity for super::SetReducerFlags {
    fn create_test_entity(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_test_entity", flags);
    }
}
