// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateAccountArgs {
    pub username: String,
    pub password: String,
}

impl From<CreateAccountArgs> for super::Reducer {
    fn from(args: CreateAccountArgs) -> Self {
        Self::CreateAccount {
            username: args.username,
            password: args.password,
        }
    }
}

impl __sdk::InModule for CreateAccountArgs {
    type Module = super::RemoteModule;
}

pub struct CreateAccountCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_account`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_account {
    /// Request that the remote module invoke the reducer `create_account` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_account`] callbacks.
    fn create_account(&self, username: String, password: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_account`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateAccountCallbackId`] can be passed to [`Self::remove_on_create_account`]
    /// to cancel the callback.
    fn on_create_account(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> CreateAccountCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_account`],
    /// causing it not to run in the future.
    fn remove_on_create_account(&self, callback: CreateAccountCallbackId);
}

impl create_account for super::RemoteReducers {
    fn create_account(&self, username: String, password: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_account", CreateAccountArgs { username, password })
    }
    fn on_create_account(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> CreateAccountCallbackId {
        CreateAccountCallbackId(self.imp.on_reducer(
            "create_account",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateAccount { username, password },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, username, password)
            }),
        ))
    }
    fn remove_on_create_account(&self, callback: CreateAccountCallbackId) {
        self.imp.remove_on_reducer("create_account", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_account`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_account {
    /// Set the call-reducer flags for the reducer `create_account` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_account(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_account for super::SetReducerFlags {
    fn create_account(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_account", flags);
    }
}
