// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCharacterArgs {
    pub name: String,
}

impl From<CreateCharacterArgs> for super::Reducer {
    fn from(args: CreateCharacterArgs) -> Self {
        Self::CreateCharacter { name: args.name }
    }
}

impl __sdk::InModule for CreateCharacterArgs {
    type Module = super::RemoteModule;
}

pub struct CreateCharacterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_character {
    /// Request that the remote module invoke the reducer `create_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_character`] callbacks.
    fn create_character(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_character`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateCharacterCallbackId`] can be passed to [`Self::remove_on_create_character`]
    /// to cancel the callback.
    fn on_create_character(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateCharacterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_character`],
    /// causing it not to run in the future.
    fn remove_on_create_character(&self, callback: CreateCharacterCallbackId);
}

impl create_character for super::RemoteReducers {
    fn create_character(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("create_character", CreateCharacterArgs { name })
    }
    fn on_create_character(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> CreateCharacterCallbackId {
        CreateCharacterCallbackId(self.imp.on_reducer(
            "create_character",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CreateCharacter { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_create_character(&self, callback: CreateCharacterCallbackId) {
        self.imp.remove_on_reducer("create_character", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_character`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_character {
    /// Set the call-reducer flags for the reducer `create_character` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_character(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_character for super::SetReducerFlags {
    fn create_character(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_character", flags);
    }
}
