// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateRoomGridArgs {
    pub center_x: i32,
    pub center_y: i32,
    pub size: u32,
}

impl From<CreateRoomGridArgs> for super::Reducer {
    fn from(args: CreateRoomGridArgs) -> Self {
        Self::CreateRoomGrid {
            center_x: args.center_x,
            center_y: args.center_y,
            size: args.size,
        }
    }
}

impl __sdk::InModule for CreateRoomGridArgs {
    type Module = super::RemoteModule;
}

pub struct CreateRoomGridCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_room_grid`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_room_grid {
    /// Request that the remote module invoke the reducer `create_room_grid` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_create_room_grid`] callbacks.
    fn create_room_grid(&self, center_x: i32, center_y: i32, size: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `create_room_grid`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CreateRoomGridCallbackId`] can be passed to [`Self::remove_on_create_room_grid`]
    /// to cancel the callback.
    fn on_create_room_grid(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &u32) + Send + 'static,
    ) -> CreateRoomGridCallbackId;
    /// Cancel a callback previously registered by [`Self::on_create_room_grid`],
    /// causing it not to run in the future.
    fn remove_on_create_room_grid(&self, callback: CreateRoomGridCallbackId);
}

impl create_room_grid for super::RemoteReducers {
    fn create_room_grid(&self, center_x: i32, center_y: i32, size: u32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "create_room_grid",
            CreateRoomGridArgs {
                center_x,
                center_y,
                size,
            },
        )
    }
    fn on_create_room_grid(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &i32, &u32) + Send + 'static,
    ) -> CreateRoomGridCallbackId {
        CreateRoomGridCallbackId(self.imp.on_reducer(
            "create_room_grid",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CreateRoomGrid {
                                    center_x,
                                    center_y,
                                    size,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, center_x, center_y, size)
            }),
        ))
    }
    fn remove_on_create_room_grid(&self, callback: CreateRoomGridCallbackId) {
        self.imp.remove_on_reducer("create_room_grid", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `create_room_grid`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_create_room_grid {
    /// Set the call-reducer flags for the reducer `create_room_grid` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn create_room_grid(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_create_room_grid for super::SetReducerFlags {
    fn create_room_grid(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("create_room_grid", flags);
    }
}
