// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::entity_type_type::EntityType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Entity {
    pub id: u64,
    pub identity: Option<__sdk::Identity>,
    pub entity_type: EntityType,
    pub name: String,
    pub description: String,
    pub room_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub volume: f32,
    pub weight: f32,
    pub max_capacity: f32,
    pub hp: i32,
    pub max_hp: i32,
    pub stamina: i32,
    pub max_stamina: i32,
    pub mana: i32,
    pub max_mana: i32,
    pub dexterity: u8,
    pub strength: u8,
    pub vitality: u8,
    pub perception: u8,
    pub willpower: u8,
    pub is_alive: bool,
    pub is_active: bool,
    pub created_at: i64,
    pub last_action_at: i64,
}

impl __sdk::InModule for Entity {
    type Module = super::RemoteModule;
}
