// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::exit_type::Exit;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `exit`.
///
/// Obtain a handle from the [`ExitTableAccess::exit`] method on [`super::RemoteTables`],
/// like `ctx.db.exit()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.exit().on_insert(...)`.
pub struct ExitTableHandle<'ctx> {
    imp: __sdk::TableHandle<Exit>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `exit`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExitTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ExitTableHandle`], which mediates access to the table `exit`.
    fn exit(&self) -> ExitTableHandle<'_>;
}

impl ExitTableAccess for super::RemoteTables {
    fn exit(&self) -> ExitTableHandle<'_> {
        ExitTableHandle {
            imp: self.imp.get_table::<Exit>("exit"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ExitInsertCallbackId(__sdk::CallbackId);
pub struct ExitDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ExitTableHandle<'ctx> {
    type Row = Exit;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Exit> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ExitInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExitInsertCallbackId {
        ExitInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExitInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ExitDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExitDeleteCallbackId {
        ExitDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ExitDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Exit>("exit");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct ExitUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ExitTableHandle<'ctx> {
    type UpdateCallbackId = ExitUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ExitUpdateCallbackId {
        ExitUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ExitUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Exit>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Exit>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `exit`,
/// which allows point queries on the field of the same name
/// via the [`ExitIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.exit().id().find(...)`.
pub struct ExitIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Exit, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ExitTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `exit`.
    pub fn id(&self) -> ExitIdUnique<'ctx> {
        ExitIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ExitIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Exit> {
        self.imp.find(col_val)
    }
}
