// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::event_type_type::EventType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GameEvent {
    pub id: u64,
    pub room_id: u64,
    pub timestamp: i64,
    pub event_type: EventType,
    pub event_data: String,
    pub primary_actor: u64,
    pub secondary_actor: Option<u64>,
    pub requires_sight: bool,
    pub requires_hearing: bool,
    pub stealth_dc: Option<u8>,
    pub expires_at: i64,
}

impl __sdk::InModule for GameEvent {
    type Module = super::RemoteModule;
}
