// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::event_type_type::EventType;
use super::game_event_type::GameEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `game_event`.
///
/// Obtain a handle from the [`GameEventTableAccess::game_event`] method on [`super::RemoteTables`],
/// like `ctx.db.game_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_event().on_insert(...)`.
pub struct GameEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<GameEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `game_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GameEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GameEventTableHandle`], which mediates access to the table `game_event`.
    fn game_event(&self) -> GameEventTableHandle<'_>;
}

impl GameEventTableAccess for super::RemoteTables {
    fn game_event(&self) -> GameEventTableHandle<'_> {
        GameEventTableHandle {
            imp: self.imp.get_table::<GameEvent>("game_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GameEventInsertCallbackId(__sdk::CallbackId);
pub struct GameEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GameEventTableHandle<'ctx> {
    type Row = GameEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GameEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GameEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEventInsertCallbackId {
        GameEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GameEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GameEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GameEventDeleteCallbackId {
        GameEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GameEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GameEvent>("game_event");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct GameEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GameEventTableHandle<'ctx> {
    type UpdateCallbackId = GameEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GameEventUpdateCallbackId {
        GameEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GameEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GameEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GameEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `game_event`,
/// which allows point queries on the field of the same name
/// via the [`GameEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.game_event().id().find(...)`.
pub struct GameEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GameEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GameEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `game_event`.
    pub fn id(&self) -> GameEventIdUnique<'ctx> {
        GameEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GameEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GameEvent> {
        self.imp.find(col_val)
    }
}
