// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::armor_type_type::ArmorType;
use super::damage_type_type::DamageType;
use super::equip_slot_type::EquipSlot;
use super::item_type_type::ItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemData {
    pub entity_id: u64,
    pub item_type: ItemType,
    pub quantity: u32,
    pub max_stack: u32,
    pub base_damage: u16,
    pub damage_type: DamageType,
    pub attack_speed: f32,
    pub armor_rating: u16,
    pub armor_type: ArmorType,
    pub internal_volume: f32,
    pub weight_reduction: f32,
    pub durability: u16,
    pub max_durability: u16,
    pub is_equipped: bool,
    pub equipped_slot: Option<EquipSlot>,
}

impl __sdk::InModule for ItemData {
    type Module = super::RemoteModule;
}
