// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::armor_type_type::ArmorType;
use super::damage_type_type::DamageType;
use super::equip_slot_type::EquipSlot;
use super::item_data_type::ItemData;
use super::item_type_type::ItemType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_data`.
///
/// Obtain a handle from the [`ItemDataTableAccess::item_data`] method on [`super::RemoteTables`],
/// like `ctx.db.item_data()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_data().on_insert(...)`.
pub struct ItemDataTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemData>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_data`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemDataTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemDataTableHandle`], which mediates access to the table `item_data`.
    fn item_data(&self) -> ItemDataTableHandle<'_>;
}

impl ItemDataTableAccess for super::RemoteTables {
    fn item_data(&self) -> ItemDataTableHandle<'_> {
        ItemDataTableHandle {
            imp: self.imp.get_table::<ItemData>("item_data"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemDataInsertCallbackId(__sdk::CallbackId);
pub struct ItemDataDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemDataTableHandle<'ctx> {
    type Row = ItemData;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemData> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemDataInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDataInsertCallbackId {
        ItemDataInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemDataInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemDataDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemDataDeleteCallbackId {
        ItemDataDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemDataDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemData>("item_data");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct ItemDataUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemDataTableHandle<'ctx> {
    type UpdateCallbackId = ItemDataUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemDataUpdateCallbackId {
        ItemDataUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemDataUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemData>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemData>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `item_data`,
/// which allows point queries on the field of the same name
/// via the [`ItemDataEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_data().entity_id().find(...)`.
pub struct ItemDataEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemData, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemDataTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `item_data`.
    pub fn entity_id(&self) -> ItemDataEntityIdUnique<'ctx> {
        ItemDataEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemDataEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ItemData> {
        self.imp.find(col_val)
    }
}
