// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.3 (commit 02449737ca3b29e7e39679fccbef541a50f32094).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod account_table;
pub mod account_type;
pub mod action_type_type;
pub mod ai_type_type;
pub mod armor_type_type;
pub mod attack_reducer;
pub mod bank_account_table;
pub mod bank_account_type;
pub mod biome_type_type;
pub mod client_connected_reducer;
pub mod client_disconnected_reducer;
pub mod client_type_type;
pub mod climate_type_type;
pub mod condition_table;
pub mod condition_type;
pub mod condition_type_type;
pub mod containment_table;
pub mod containment_type;
pub mod create_account_reducer;
pub mod create_character_reducer;
pub mod create_room_grid_reducer;
pub mod create_test_entity_reducer;
pub mod create_test_region_reducer;
pub mod create_test_room_reducer;
pub mod damage_type_type;
pub mod entity_table;
pub mod entity_type;
pub mod entity_type_type;
pub mod equip_slot_type;
pub mod event_type_type;
pub mod exit_table;
pub mod exit_type;
pub mod game_event_table;
pub mod game_event_type;
pub mod item_data_table;
pub mod item_data_type;
pub mod item_type_type;
pub mod login_reducer;
pub mod look_reducer;
pub mod move_player_reducer;
pub mod movement_type_type;
pub mod npc_behavior_table;
pub mod npc_behavior_type;
pub mod npc_role_type;
pub mod player_session_table;
pub mod player_session_type;
pub mod rate_limit_table;
pub mod rate_limit_type;
pub mod region_table;
pub mod region_type;
pub mod room_table;
pub mod room_type;
pub mod server_config_table;
pub mod server_config_type;
pub mod skill_table;
pub mod skill_type;
pub mod skill_type_type;
pub mod whoami_reducer;

pub use account_table::*;
pub use account_type::Account;
pub use action_type_type::ActionType;
pub use ai_type_type::AiType;
pub use armor_type_type::ArmorType;
pub use attack_reducer::{attack, set_flags_for_attack, AttackCallbackId};
pub use bank_account_table::*;
pub use bank_account_type::BankAccount;
pub use biome_type_type::BiomeType;
pub use client_connected_reducer::{
    client_connected, set_flags_for_client_connected, ClientConnectedCallbackId,
};
pub use client_disconnected_reducer::{
    client_disconnected, set_flags_for_client_disconnected, ClientDisconnectedCallbackId,
};
pub use client_type_type::ClientType;
pub use climate_type_type::ClimateType;
pub use condition_table::*;
pub use condition_type::Condition;
pub use condition_type_type::ConditionType;
pub use containment_table::*;
pub use containment_type::Containment;
pub use create_account_reducer::{
    create_account, set_flags_for_create_account, CreateAccountCallbackId,
};
pub use create_character_reducer::{
    create_character, set_flags_for_create_character, CreateCharacterCallbackId,
};
pub use create_room_grid_reducer::{
    create_room_grid, set_flags_for_create_room_grid, CreateRoomGridCallbackId,
};
pub use create_test_entity_reducer::{
    create_test_entity, set_flags_for_create_test_entity, CreateTestEntityCallbackId,
};
pub use create_test_region_reducer::{
    create_test_region, set_flags_for_create_test_region, CreateTestRegionCallbackId,
};
pub use create_test_room_reducer::{
    create_test_room, set_flags_for_create_test_room, CreateTestRoomCallbackId,
};
pub use damage_type_type::DamageType;
pub use entity_table::*;
pub use entity_type::Entity;
pub use entity_type_type::EntityType;
pub use equip_slot_type::EquipSlot;
pub use event_type_type::EventType;
pub use exit_table::*;
pub use exit_type::Exit;
pub use game_event_table::*;
pub use game_event_type::GameEvent;
pub use item_data_table::*;
pub use item_data_type::ItemData;
pub use item_type_type::ItemType;
pub use login_reducer::{login, set_flags_for_login, LoginCallbackId};
pub use look_reducer::{look, set_flags_for_look, LookCallbackId};
pub use move_player_reducer::{move_player, set_flags_for_move_player, MovePlayerCallbackId};
pub use movement_type_type::MovementType;
pub use npc_behavior_table::*;
pub use npc_behavior_type::NpcBehavior;
pub use npc_role_type::NpcRole;
pub use player_session_table::*;
pub use player_session_type::PlayerSession;
pub use rate_limit_table::*;
pub use rate_limit_type::RateLimit;
pub use region_table::*;
pub use region_type::Region;
pub use room_table::*;
pub use room_type::Room;
pub use server_config_table::*;
pub use server_config_type::ServerConfig;
pub use skill_table::*;
pub use skill_type::Skill;
pub use skill_type_type::SkillType;
pub use whoami_reducer::{set_flags_for_whoami, whoami, WhoamiCallbackId};

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    Attack {
        target_id: u64,
    },
    ClientConnected,
    ClientDisconnected,
    CreateAccount {
        username: String,
        password: String,
    },
    CreateCharacter {
        name: String,
    },
    CreateRoomGrid {
        center_x: i32,
        center_y: i32,
        size: u32,
    },
    CreateTestEntity {
        name: String,
    },
    CreateTestRegion,
    CreateTestRoom,
    Login {
        username: String,
        password: String,
    },
    Look,
    MovePlayer {
        direction: String,
    },
    Whoami,
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::Attack { .. } => "attack",
            Reducer::ClientConnected => "client_connected",
            Reducer::ClientDisconnected => "client_disconnected",
            Reducer::CreateAccount { .. } => "create_account",
            Reducer::CreateCharacter { .. } => "create_character",
            Reducer::CreateRoomGrid { .. } => "create_room_grid",
            Reducer::CreateTestEntity { .. } => "create_test_entity",
            Reducer::CreateTestRegion => "create_test_region",
            Reducer::CreateTestRoom => "create_test_room",
            Reducer::Login { .. } => "login",
            Reducer::Look => "look",
            Reducer::MovePlayer { .. } => "move_player",
            Reducer::Whoami => "whoami",
            _ => unreachable!(),
        }
    }
}
impl TryFrom<__ws::ReducerCallInfo<__ws::BsatnFormat>> for Reducer {
    type Error = __sdk::Error;
    fn try_from(value: __ws::ReducerCallInfo<__ws::BsatnFormat>) -> __sdk::Result<Self> {
        match &value.reducer_name[..] {
            "attack" => Ok(__sdk::parse_reducer_args::<attack_reducer::AttackArgs>(
                "attack",
                &value.args,
            )?
            .into()),
            "client_connected" => Ok(__sdk::parse_reducer_args::<
                client_connected_reducer::ClientConnectedArgs,
            >("client_connected", &value.args)?
            .into()),
            "client_disconnected" => Ok(__sdk::parse_reducer_args::<
                client_disconnected_reducer::ClientDisconnectedArgs,
            >("client_disconnected", &value.args)?
            .into()),
            "create_account" => Ok(__sdk::parse_reducer_args::<
                create_account_reducer::CreateAccountArgs,
            >("create_account", &value.args)?
            .into()),
            "create_character" => Ok(__sdk::parse_reducer_args::<
                create_character_reducer::CreateCharacterArgs,
            >("create_character", &value.args)?
            .into()),
            "create_room_grid" => Ok(__sdk::parse_reducer_args::<
                create_room_grid_reducer::CreateRoomGridArgs,
            >("create_room_grid", &value.args)?
            .into()),
            "create_test_entity" => Ok(__sdk::parse_reducer_args::<
                create_test_entity_reducer::CreateTestEntityArgs,
            >("create_test_entity", &value.args)?
            .into()),
            "create_test_region" => Ok(__sdk::parse_reducer_args::<
                create_test_region_reducer::CreateTestRegionArgs,
            >("create_test_region", &value.args)?
            .into()),
            "create_test_room" => Ok(__sdk::parse_reducer_args::<
                create_test_room_reducer::CreateTestRoomArgs,
            >("create_test_room", &value.args)?
            .into()),
            "login" => Ok(__sdk::parse_reducer_args::<login_reducer::LoginArgs>(
                "login",
                &value.args,
            )?
            .into()),
            "look" => Ok(
                __sdk::parse_reducer_args::<look_reducer::LookArgs>("look", &value.args)?.into(),
            ),
            "move_player" => Ok(
                __sdk::parse_reducer_args::<move_player_reducer::MovePlayerArgs>(
                    "move_player",
                    &value.args,
                )?
                .into(),
            ),
            "whoami" => Ok(__sdk::parse_reducer_args::<whoami_reducer::WhoamiArgs>(
                "whoami",
                &value.args,
            )?
            .into()),
            unknown => {
                Err(
                    __sdk::InternalError::unknown_name("reducer", unknown, "ReducerCallInfo")
                        .into(),
                )
            }
        }
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    account: __sdk::TableUpdate<Account>,
    bank_account: __sdk::TableUpdate<BankAccount>,
    condition: __sdk::TableUpdate<Condition>,
    containment: __sdk::TableUpdate<Containment>,
    entity: __sdk::TableUpdate<Entity>,
    exit: __sdk::TableUpdate<Exit>,
    game_event: __sdk::TableUpdate<GameEvent>,
    item_data: __sdk::TableUpdate<ItemData>,
    npc_behavior: __sdk::TableUpdate<NpcBehavior>,
    player_session: __sdk::TableUpdate<PlayerSession>,
    rate_limit: __sdk::TableUpdate<RateLimit>,
    region: __sdk::TableUpdate<Region>,
    room: __sdk::TableUpdate<Room>,
    server_config: __sdk::TableUpdate<ServerConfig>,
    skill: __sdk::TableUpdate<Skill>,
}

impl TryFrom<__ws::DatabaseUpdate<__ws::BsatnFormat>> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::DatabaseUpdate<__ws::BsatnFormat>) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in raw.tables {
            match &table_update.table_name[..] {
                "account" => db_update
                    .account
                    .append(account_table::parse_table_update(table_update)?),
                "bank_account" => db_update
                    .bank_account
                    .append(bank_account_table::parse_table_update(table_update)?),
                "condition" => db_update
                    .condition
                    .append(condition_table::parse_table_update(table_update)?),
                "containment" => db_update
                    .containment
                    .append(containment_table::parse_table_update(table_update)?),
                "entity" => db_update
                    .entity
                    .append(entity_table::parse_table_update(table_update)?),
                "exit" => db_update
                    .exit
                    .append(exit_table::parse_table_update(table_update)?),
                "game_event" => db_update
                    .game_event
                    .append(game_event_table::parse_table_update(table_update)?),
                "item_data" => db_update
                    .item_data
                    .append(item_data_table::parse_table_update(table_update)?),
                "npc_behavior" => db_update
                    .npc_behavior
                    .append(npc_behavior_table::parse_table_update(table_update)?),
                "player_session" => db_update
                    .player_session
                    .append(player_session_table::parse_table_update(table_update)?),
                "rate_limit" => db_update
                    .rate_limit
                    .append(rate_limit_table::parse_table_update(table_update)?),
                "region" => db_update
                    .region
                    .append(region_table::parse_table_update(table_update)?),
                "room" => db_update
                    .room
                    .append(room_table::parse_table_update(table_update)?),
                "server_config" => db_update
                    .server_config
                    .append(server_config_table::parse_table_update(table_update)?),
                "skill" => db_update
                    .skill
                    .append(skill_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.account = cache
            .apply_diff_to_table::<Account>("account", &self.account)
            .with_updates_by_pk(|row| &row.identity);
        diff.bank_account = cache
            .apply_diff_to_table::<BankAccount>("bank_account", &self.bank_account)
            .with_updates_by_pk(|row| &row.identity);
        diff.condition = cache
            .apply_diff_to_table::<Condition>("condition", &self.condition)
            .with_updates_by_pk(|row| &row.id);
        diff.containment = cache
            .apply_diff_to_table::<Containment>("containment", &self.containment)
            .with_updates_by_pk(|row| &row.id);
        diff.entity = cache
            .apply_diff_to_table::<Entity>("entity", &self.entity)
            .with_updates_by_pk(|row| &row.id);
        diff.exit = cache
            .apply_diff_to_table::<Exit>("exit", &self.exit)
            .with_updates_by_pk(|row| &row.id);
        diff.game_event = cache
            .apply_diff_to_table::<GameEvent>("game_event", &self.game_event)
            .with_updates_by_pk(|row| &row.id);
        diff.item_data = cache
            .apply_diff_to_table::<ItemData>("item_data", &self.item_data)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.npc_behavior = cache
            .apply_diff_to_table::<NpcBehavior>("npc_behavior", &self.npc_behavior)
            .with_updates_by_pk(|row| &row.entity_id);
        diff.player_session = cache
            .apply_diff_to_table::<PlayerSession>("player_session", &self.player_session)
            .with_updates_by_pk(|row| &row.identity);
        diff.rate_limit = cache
            .apply_diff_to_table::<RateLimit>("rate_limit", &self.rate_limit)
            .with_updates_by_pk(|row| &row.identity);
        diff.region = cache
            .apply_diff_to_table::<Region>("region", &self.region)
            .with_updates_by_pk(|row| &row.id);
        diff.room = cache
            .apply_diff_to_table::<Room>("room", &self.room)
            .with_updates_by_pk(|row| &row.id);
        diff.server_config = cache
            .apply_diff_to_table::<ServerConfig>("server_config", &self.server_config)
            .with_updates_by_pk(|row| &row.key);
        diff.skill = cache
            .apply_diff_to_table::<Skill>("skill", &self.skill)
            .with_updates_by_pk(|row| &row.id);

        diff
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    account: __sdk::TableAppliedDiff<'r, Account>,
    bank_account: __sdk::TableAppliedDiff<'r, BankAccount>,
    condition: __sdk::TableAppliedDiff<'r, Condition>,
    containment: __sdk::TableAppliedDiff<'r, Containment>,
    entity: __sdk::TableAppliedDiff<'r, Entity>,
    exit: __sdk::TableAppliedDiff<'r, Exit>,
    game_event: __sdk::TableAppliedDiff<'r, GameEvent>,
    item_data: __sdk::TableAppliedDiff<'r, ItemData>,
    npc_behavior: __sdk::TableAppliedDiff<'r, NpcBehavior>,
    player_session: __sdk::TableAppliedDiff<'r, PlayerSession>,
    rate_limit: __sdk::TableAppliedDiff<'r, RateLimit>,
    region: __sdk::TableAppliedDiff<'r, Region>,
    room: __sdk::TableAppliedDiff<'r, Room>,
    server_config: __sdk::TableAppliedDiff<'r, ServerConfig>,
    skill: __sdk::TableAppliedDiff<'r, Skill>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Account>("account", &self.account, event);
        callbacks.invoke_table_row_callbacks::<BankAccount>(
            "bank_account",
            &self.bank_account,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Condition>("condition", &self.condition, event);
        callbacks.invoke_table_row_callbacks::<Containment>(
            "containment",
            &self.containment,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Entity>("entity", &self.entity, event);
        callbacks.invoke_table_row_callbacks::<Exit>("exit", &self.exit, event);
        callbacks.invoke_table_row_callbacks::<GameEvent>("game_event", &self.game_event, event);
        callbacks.invoke_table_row_callbacks::<ItemData>("item_data", &self.item_data, event);
        callbacks.invoke_table_row_callbacks::<NpcBehavior>(
            "npc_behavior",
            &self.npc_behavior,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSession>(
            "player_session",
            &self.player_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RateLimit>("rate_limit", &self.rate_limit, event);
        callbacks.invoke_table_row_callbacks::<Region>("region", &self.region, event);
        callbacks.invoke_table_row_callbacks::<Room>("room", &self.room, event);
        callbacks.invoke_table_row_callbacks::<ServerConfig>(
            "server_config",
            &self.server_config,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Skill>("skill", &self.skill, event);
    }
}

#[doc(hidden)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

#[doc(hidden)]
/// The `set_reducer_flags` field of [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
/// Each method sets the flags for the reducer with the same name.
///
/// This type is currently unstable and may be removed without a major version bump.
pub struct SetReducerFlags {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for SetReducerFlags {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
/// - [`DbConnection::run_threaded`].
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
/// - [`DbConnection::advance_one_message_blocking`].
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SetReducerFlags = SetReducerFlags,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SetReducerFlags = SetReducerFlags,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to setting the call-flags of each reducer defined for each reducer defined by the module
    /// via extension traits implemented for [`SetReducerFlags`].
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    pub set_reducer_flags: SetReducerFlags,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            set_reducer_flags: SetReducerFlags { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type SetReducerFlags = SetReducerFlags;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }
    fn set_reducer_flags(&self) -> &Self::SetReducerFlags {
        &self.set_reducer_flags
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type SetReducerFlags = SetReducerFlags;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        account_table::register_table(client_cache);
        bank_account_table::register_table(client_cache);
        condition_table::register_table(client_cache);
        containment_table::register_table(client_cache);
        entity_table::register_table(client_cache);
        exit_table::register_table(client_cache);
        game_event_table::register_table(client_cache);
        item_data_table::register_table(client_cache);
        npc_behavior_table::register_table(client_cache);
        player_session_table::register_table(client_cache);
        rate_limit_table::register_table(client_cache);
        region_table::register_table(client_cache);
        room_table::register_table(client_cache);
        server_config_table::register_table(client_cache);
        skill_table::register_table(client_cache);
    }
}
