// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ai_type_type::AiType;
use super::movement_type_type::MovementType;
use super::npc_role_type::NpcRole;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcBehavior {
    pub entity_id: u64,
    pub ai_type: AiType,
    pub aggro_range: u8,
    pub wander_range: u8,
    pub home_room: u64,
    pub role: Option<NpcRole>,
    pub movement_type: MovementType,
    pub patrol_waypoints: String,
    pub movement_speed: f32,
    pub faction: Option<String>,
    pub assist_allies: bool,
    pub respawn_delay: u32,
    pub is_unique: bool,
    pub can_talk: bool,
    pub dialogue_tree_id: Option<u64>,
    pub loot_table_id: Option<u64>,
}

impl __sdk::InModule for NpcBehavior {
    type Module = super::RemoteModule;
}
