// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ai_type_type::AiType;
use super::movement_type_type::MovementType;
use super::npc_behavior_type::NpcBehavior;
use super::npc_role_type::NpcRole;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_behavior`.
///
/// Obtain a handle from the [`NpcBehaviorTableAccess::npc_behavior`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_behavior()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_behavior().on_insert(...)`.
pub struct NpcBehaviorTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcBehavior>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_behavior`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcBehaviorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcBehaviorTableHandle`], which mediates access to the table `npc_behavior`.
    fn npc_behavior(&self) -> NpcBehaviorTableHandle<'_>;
}

impl NpcBehaviorTableAccess for super::RemoteTables {
    fn npc_behavior(&self) -> NpcBehaviorTableHandle<'_> {
        NpcBehaviorTableHandle {
            imp: self.imp.get_table::<NpcBehavior>("npc_behavior"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcBehaviorInsertCallbackId(__sdk::CallbackId);
pub struct NpcBehaviorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcBehaviorTableHandle<'ctx> {
    type Row = NpcBehavior;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcBehavior> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcBehaviorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBehaviorInsertCallbackId {
        NpcBehaviorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcBehaviorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcBehaviorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBehaviorDeleteCallbackId {
        NpcBehaviorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcBehaviorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcBehavior>("npc_behavior");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct NpcBehaviorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcBehaviorTableHandle<'ctx> {
    type UpdateCallbackId = NpcBehaviorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcBehaviorUpdateCallbackId {
        NpcBehaviorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcBehaviorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<NpcBehavior>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcBehavior>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `npc_behavior`,
/// which allows point queries on the field of the same name
/// via the [`NpcBehaviorEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_behavior().entity_id().find(...)`.
pub struct NpcBehaviorEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcBehavior, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcBehaviorTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `npc_behavior`.
    pub fn entity_id(&self) -> NpcBehaviorEntityIdUnique<'ctx> {
        NpcBehaviorEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcBehaviorEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcBehavior> {
        self.imp.find(col_val)
    }
}
