// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::client_type_type::ClientType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSession {
    pub identity: __sdk::Identity,
    pub character_id: u64,
    pub connected_at: i64,
    pub last_heartbeat: i64,
    pub client_type: ClientType,
    pub client_version: String,
    pub is_active: bool,
}

impl __sdk::InModule for PlayerSession {
    type Module = super::RemoteModule;
}
