// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::action_type_type::ActionType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RateLimit {
    pub identity: __sdk::Identity,
    pub action_type: ActionType,
    pub count: u32,
    pub window_start: i64,
    pub last_action: i64,
}

impl __sdk::InModule for RateLimit {
    type Module = super::RemoteModule;
}
