// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::biome_type_type::BiomeType;
use super::climate_type_type::ClimateType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Region {
    pub id: u64,
    pub name: String,
    pub description: String,
    pub biome: BiomeType,
    pub climate: ClimateType,
    pub base_temperature: i16,
    pub base_light_level: u8,
    pub default_spawn_room: u64,
    pub is_active: bool,
    pub tick_rate_fast: u32,
    pub tick_rate_medium: u32,
    pub min_x: Option<f32>,
    pub max_x: Option<f32>,
    pub min_y: Option<f32>,
    pub max_y: Option<f32>,
}

impl __sdk::InModule for Region {
    type Module = super::RemoteModule;
}
