// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Room {
    pub id: u64,
    pub region_id: u64,
    pub name: String,
    pub description: String,
    pub north_exit: Option<u64>,
    pub south_exit: Option<u64>,
    pub east_exit: Option<u64>,
    pub west_exit: Option<u64>,
    pub up_exit: Option<u64>,
    pub down_exit: Option<u64>,
    pub has_special_exits: bool,
    pub temperature_modifier: i16,
    pub light_modifier: i16,
    pub is_safe_zone: bool,
    pub allows_combat: bool,
    pub allows_magic: bool,
    pub current_volume: Option<f32>,
    pub max_volume: Option<f32>,
    pub is_active: bool,
}

impl __sdk::InModule for Room {
    type Module = super::RemoteModule;
}
