// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::room_type::Room;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `room`.
///
/// Obtain a handle from the [`RoomTableAccess::room`] method on [`super::RemoteTables`],
/// like `ctx.db.room()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room().on_insert(...)`.
pub struct RoomTableHandle<'ctx> {
    imp: __sdk::TableHandle<Room>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `room`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoomTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoomTableHandle`], which mediates access to the table `room`.
    fn room(&self) -> RoomTableHandle<'_>;
}

impl RoomTableAccess for super::RemoteTables {
    fn room(&self) -> RoomTableHandle<'_> {
        RoomTableHandle {
            imp: self.imp.get_table::<Room>("room"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoomInsertCallbackId(__sdk::CallbackId);
pub struct RoomDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RoomTableHandle<'ctx> {
    type Row = Room;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Room> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoomInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomInsertCallbackId {
        RoomInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoomInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoomDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoomDeleteCallbackId {
        RoomDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoomDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Room>("room");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct RoomUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoomTableHandle<'ctx> {
    type UpdateCallbackId = RoomUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoomUpdateCallbackId {
        RoomUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoomUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Room>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Room>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `room`,
/// which allows point queries on the field of the same name
/// via the [`RoomIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.room().id().find(...)`.
pub struct RoomIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Room, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoomTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `room`.
    pub fn id(&self) -> RoomIdUnique<'ctx> {
        RoomIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoomIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Room> {
        self.imp.find(col_val)
    }
}
