// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ServerConfig {
    pub key: String,
    pub value: String,
    pub last_updated: i64,
    pub updated_by: Option<__sdk::Identity>,
}

impl __sdk::InModule for ServerConfig {
    type Module = super::RemoteModule;
}
