// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skill_type::Skill;
use super::skill_type_type::SkillType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill`.
///
/// Obtain a handle from the [`SkillTableAccess::skill`] method on [`super::RemoteTables`],
/// like `ctx.db.skill()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill().on_insert(...)`.
pub struct SkillTableHandle<'ctx> {
    imp: __sdk::TableHandle<Skill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillTableHandle`], which mediates access to the table `skill`.
    fn skill(&self) -> SkillTableHandle<'_>;
}

impl SkillTableAccess for super::RemoteTables {
    fn skill(&self) -> SkillTableHandle<'_> {
        SkillTableHandle {
            imp: self.imp.get_table::<Skill>("skill"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillInsertCallbackId(__sdk::CallbackId);
pub struct SkillDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SkillTableHandle<'ctx> {
    type Row = Skill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Skill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillInsertCallbackId {
        SkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillDeleteCallbackId {
        SkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Skill>("skill");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SkillUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillTableHandle<'ctx> {
    type UpdateCallbackId = SkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillUpdateCallbackId {
        SkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Skill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Skill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `skill`,
/// which allows point queries on the field of the same name
/// via the [`SkillIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill().id().find(...)`.
pub struct SkillIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Skill, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `skill`.
    pub fn id(&self) -> SkillIdUnique<'ctx> {
        SkillIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Skill> {
        self.imp.find(col_val)
    }
}
