// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::skill_type_type::SkillType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Skill {
    pub id: u64,
    pub entity_id: u64,
    pub skill_type: SkillType,
    pub level: u8,
    pub experience: u32,
    pub last_used: i64,
    pub times_used: u32,
}

impl __sdk::InModule for Skill {
    type Module = super::RemoteModule;
}
