// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WhoamiArgs {}

impl From<WhoamiArgs> for super::Reducer {
    fn from(args: WhoamiArgs) -> Self {
        Self::Whoami
    }
}

impl __sdk::InModule for WhoamiArgs {
    type Module = super::RemoteModule;
}

pub struct WhoamiCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `whoami`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait whoami {
    /// Request that the remote module invoke the reducer `whoami` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_whoami`] callbacks.
    fn whoami(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `whoami`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`WhoamiCallbackId`] can be passed to [`Self::remove_on_whoami`]
    /// to cancel the callback.
    fn on_whoami(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> WhoamiCallbackId;
    /// Cancel a callback previously registered by [`Self::on_whoami`],
    /// causing it not to run in the future.
    fn remove_on_whoami(&self, callback: WhoamiCallbackId);
}

impl whoami for super::RemoteReducers {
    fn whoami(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("whoami", WhoamiArgs {})
    }
    fn on_whoami(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> WhoamiCallbackId {
        WhoamiCallbackId(self.imp.on_reducer(
            "whoami",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Whoami {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_whoami(&self, callback: WhoamiCallbackId) {
        self.imp.remove_on_reducer("whoami", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `whoami`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_whoami {
    /// Set the call-reducer flags for the reducer `whoami` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn whoami(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_whoami for super::SetReducerFlags {
    fn whoami(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("whoami", flags);
    }
}
